# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "http://pet.leg.ufpr.br/"
DefaultContentLanguage  = "pt"
publishDir              = "docs"
# canonifyURLs            = "true"
# relativeURLs            = "true"
title                   = "PET Estatística UFPR"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = "UA-174760536-1"
pluralizeListTitles     = false
disableLanguages        = ["en", "fr", "pl", "de", "es", "zh-CN", "zh-TW", "ja"]
ignoreFiles             = ["\\.R$", "\\.Rmd$", "\\.Rproj$", "\\.sh$", "\\.txt$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "linkedin", "email"]

  [params.meta]
    description         = "Site oficial do PET Estatística UFPR"
    author              = "Membros do PET Estatística UFPR"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "PET Estatística UFPR"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "PET Estatística UFPR"
    paragraph             = "Programa de Educação Tutorial (PET) do curso de Estatística da UFPR"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo-pet-azul-logo.png"
      shape               = "circle"
      width               = ""
      alt                 = "PET Estatística UFPR"

  [params.sidebar]
    about               = "O PET Estatística foi fundado com o intuito de oferecer aos alunos da graduação, a possibilidade de ampliar o conhecimento e a interação com os professores do departamento."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Sobre"
    identifier        = "about"
    url               = "/sobre/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Integrantes"
    identifier        = "integrantes"
    url               = "/integrantes/"
    pre               = "<i class='fas fa-users'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Projetos"
    identifier        = "projetos"
    url               = "/projetos/"
    pre               = "<i class='fas fa-terminal'></i>"
    weight            = 8

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contato"
    identifier        = "contact"
    url               = "/contato/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

  [[menu.main]]
    name              = "Processo Seletivo"
    identifier        = "selecao"
    url               = "/selecao/"
    pre               = "<i class='fas fa-bullhorn'></i>"
    weight            = 7

  [[menu.main]]
    name              = "Semana Acadêmica"
    identifier        = "semana"
    url               = "/semana/"
    pre               = "<i class='fas fa-graduation-cap'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Categorias"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 9


[social]
  # Coding Communities
  github                = "pet-estatistica"
  # Visual Art Communities
  # flickr                = "example"
  # Publishing Communities
  # medium                = ""
  # Professional/Business Oriented Communities
  # linkedin              = "example"
  linkedin_company      = "pet-estatistica-ufpr"
  # slideshare            = ""
  # Social Networks
  facebook              = "PET.Estatistica.UFPR"
  youtube               = "channel/UCPFo2Z9zZeB-Xgg8sm9sBKg"
  # whatsapp              = "" # WhatsApp Number
  instagram             = "pet.est.ufpr"
  # twitter               = "example"
  # telegram              = "example"
  # Email
  email                 = "pet.estatistica.ufpr@gmail.com"
