#baseURL       = "https://pet-estatistica.netlify.app/"
baseURL       = "https://pet.leg.ufpr.br/"
languageCode  = "pt-br"
DefaultContentLanguage = "pt"
title         = "PET ESTATÍSTICA UFPR"
theme = "roxo-hugo"
summarylength = 25
removePathAccents = true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "INÍCIO"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "SOBRE"
    url     = "sobre"
    weight  = 2
  [[menu.nav]]
    name    = "PROCESSOS"
    url     = "processos"
    weight  = 3    
  [[menu.nav]]
    name    = "INTEGRANTES"
    url     = "integrantes"
    weight  = 4
  [[menu.nav]]
    name    = "DOCENTES"
    url     = "docentes"
    weight  = 5    
  [[menu.nav]]
    name    = "REDES SOCIAIS"
    url     = "redessociais"
    weight  = 6
  [[menu.nav]]
    name    = "ATIVIDADES"
    url     = "atividades"
    weight  = 7
  [[menu.nav]]
    name    = "MATERIAIS"
    url     = "materiais"
    weight  = 8
  [[menu.nav]]
    name    = "CONTATO"
    url     = "contato"
    weight  = 9

[params.contact]
  email = "pet.estatistica.ufpr@gmail.com"
  phone = "+55 (41) 3361-3141"
  address = "Rua Cel. Francisco Heráclito dos Santos, 100<br>Centro Politécnico - Jardim das Américas<br>Edifício do Setor de Ciências Exatas<br>Sala PET Estatística - 2º andar "
  map_link = "https://maps.app.goo.gl/5MecemxyFy8d6bnn9"
  map_embed = '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3602.6452716283666!2d-49.23361262286281!3d-25.450120377548988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94dce510e045c49b%3A0x90820299a35dbf7f!2sDepartamento%20de%20Estat%C3%ADstica%20-%20UFPR!5e0!3m2!1spt-BR!2sbr!4v1745109360582!5m2!1spt-BR!2sbr" width="1200" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
  
[[params.contact.social]]
  icon = "fa fa-github"
  link = "https://github.com/pet-estatistica"
  
[[params.contact.social]]
  icon = "fa fa-linkedin"
  link = "https://www.linkedin.com/company/pet-estat%C3%ADstica-ufpr"

[[params.contact.social]]
  icon = "fa fa-youtube"
  link = "https://www.youtube.com/c/PETEstat%C3%ADsticaUFPR"

[[params.contact.social]]
  icon = "fa fa-instagram"
  link = "https://www.instagram.com/pet.est.ufpr"

[services]
  [services.googleAnalytics]
    id = "G-ZPWNNN29C7"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

# Site Params
[params]

  logo = "images/logo-pet.png"
  logo_footer = "images/logo-pet-tbg.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon-pet.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  # googleAnalitycsID = "G-4QGDQVC922"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"
  tokenInstagram = "IGAANtnh5nLCdBZAFRiS2RPZAjVJMUs4SE5VTWJoX1k4MWFPN25WN1dndTN0VGJkRkxpOVpRVzk2OGFSWDU3Q3FlYWZAHR29YU1BiOTdkQWJ5Sm1yQk5hcGhoOENwZAGdDal8yRk9uenVPNVpXc2FVZAERJWWdHcXFRb0cxbEZAPbjA2cwZDZD"
  
  # Banner Section
  [params.banner]
    enable                = true
    #background_image      = "images/backgrounds/dark-blue-bg.png"
    background_image      = "images/backgrounds/2025-2.png"
    heading               = "PET ESTATÍSTICA UFPR"
    tagline               = ""
    primary_button        = "Veja nossas Atividades"
    primary_button_url    = "atividades"
    secondary_button      = "Entre em contato"
    secondary_button_url  = "contato"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "PROCESSO SELETIVO FINALIZADO"
    primary_button      = "Inscreva-se"
    primary_button_url  = "https://forms.gle/niHaxxmeTHHieQuW8"
    secondary_button    = "Mais Informações"
    secondary_button_url = "processos"
    houve_alteracoes_no_processo_seletivo = false  # Vai mostrar um banner com as informações abaixo
    titulo = "Importante!"
    mensagem = "Houveram alterações no processo seletivo 2025"
    botao_detalhes = "Confira as mudanças"
    link_detalhes = "/processos/2025-08/"
    tipo = "info"  # warning, info, error, success
    
  [params.footer]
    params.footer.qr_print = true
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informações de contato"
      address = "Rua Cel. Francisco Heráclito dos Santos, 100<br>Centro Politécnico - Jardim das Américas<br>Edifício do Setor de Ciências Exatas<br>Sala PET Estatística - 2º andar "
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Redes Sociais"
        [[params.footer.social.link]]
          name = "Github"
          url  = "https://github.com/pet-estatistica"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/company/pet-estatistica-ufpr"
        [[params.footer.social.link]]
          name = "Youtube"
          url  = "https://www.youtube.com/c/PETEstat%C3%ADsticaUFPR"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/pet.est.ufpr"
      # Footer Service
      [params.footer.service]
        title       = "PET ESTATÍSTICA"
        description = "PROGRAMA DE EDUCAÇÃO TUTORIAL (PET) DO CURSO DE ESTATÍSTICA DA UFPR"
      [params.footer.back_to_top]
        description = ""


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
